---
project_name: tssc
dist: bin/dist

builds:
  - id: tssc
    binary: tssc
    goos:
      - darwin
      - linux
      - windows
    env:
      - GOFLAGS={{ .Env.GOFLAGS }}
      - CGO_ENABLED={{ .Env.CGO_ENABLED }}
      - CGO_LDFLAGS={{ .Env.CGO_LDFLAGS }}
    main: cmd/tssc/main.go
    goarch:
      - arm64
      - amd64
    ldflags:
      - -X github.com/redhat-appstudio/tssc-cli/pkg/constants.Version={{.Version}}
