---
{{- include "common.serviceAccount" . }}
---
{{- include "common.clusterRoleBinding" . }}
{{- if .Values.subscriptions.settings.lockVersions }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Release.Name }}-installplan-approver
rules:
  - apiGroups:
      - operators.coreos.com
    resources:
      - clusterserviceversions
      - installplans
    verbs:
      - get
      - list
      - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Release.Name }}-installplan-approver
  labels: {{- include "common.postDeployDeleteLabels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Release.Name }}-installplan-approver
subjects:
  - kind: ServiceAccount
    name: {{ .Release.Name }}
    namespace: {{ .Release.Namespace }}
{{- end }}