---
{{- include "common.serviceAccount" . }}
---
{{- $namespaces := dict
  "notdefaultnamespace" .Values.pipelines.namespace
  "integrationsecretnamespace" .Values.pipelines.tssc.namespace
}}
{{- include "common.secretRWRoleBinding" (merge $namespaces .) }}
