{{- $authSecret := (lookup "v1" "Secret" .Release.Namespace "tssc-authentication-integration") -}}
{{- $trustificationSecret := (lookup "v1" "Secret" .Release.Namespace "tssc-trustification-integration") -}}
{{- $authData := (get $authSecret "data") | default dict -}}
{{- $trustificationData := (get $trustificationSecret "data") | default dict -}}
{{- if and $authData $trustificationData -}}
  {{- range .Values.appNamespaces.namespace_prefixes }}
    {{- $namespace := . }}
---
kind: Secret
type: Opaque
apiVersion: v1
metadata:
  name: tpa-secret
  namespace: {{ $namespace }}-ci
data:
  bombastic_api_url: {{ $trustificationData.bombastic_api_url }}
  oidc_client_id: {{ $authData.oidc_client_id }}
  oidc_client_secret: {{ $authData.oidc_client_secret }}
  oidc_issuer_url: {{ $authData.oidc_issuer_url }}
    {{- if $trustificationData.supported_cyclonedx_version }}
  supported_cyclonedx_version: {{ $trustificationData.supported_cyclonedx_version }}
    {{- end }}
  {{- end }}
{{- end }}