apiVersion: v1
kind: Secret
metadata:
  name: tssc-quay-integration
  namespace: {{ .Release.Namespace }}
  labels: {{- include "tssc-quay.labels" . | nindent 4 }}
type: Opaque
stringData:
  url: {{ include "tssc-quay.scalarJSON" .Values.quay.url }}
  token: {{ include "tssc-quay.scalarJSON" .Values.quay.token }}
  organization: {{ include "tssc-quay.scalarJSON" .Values.quay.organization }}
  .dockerconfigjson: {{ include "tssc-quay.dockerconfigjsonQuoted" .Values.quay.dockerconfigjson }}
  .dockerconfigjsonreadonly: {{ include "tssc-quay.dockerconfigjsonReadonlyQuoted" .Values.quay.dockerconfigjsonreadonly }}
