---
apiVersion: v2
name: tssc-tpa-subscriptions
description: TSSC OpenShift Operator Hub Subscriptions
type: application
version: "1.9.0"
annotations:
  helmet.redhat-appstudio.github.com/depends-on-bundle-charts: tssc-tpa-openshift
