{{- $tpa := .Values.trustedProfileAnalyzer -}}
{{- $protocol := "http" -}}
{{- if $tpa.openshift.useServiceCa }}
  {{- $protocol = "https" }}
{{- end }}
---
apiVersion: v1
kind: Secret
metadata:
  labels:
    app: trustedprofileanalyzer
  namespace: {{ required "trustedProfileAnalyzer.integrationSecret.namespace is required" $tpa.integrationSecret.namespace }}
  name: tssc-trustification-integration
type: Opaque
stringData:
  bombastic_api_url: {{ printf "%s://server%s" $protocol $tpa.appDomain | quote }}
  supported_cyclonedx_version: {{ required "trustedProfileAnalyzer.cycloneDXVersion is required" $tpa.cycloneDXVersion | quote }}
